"""
{{ service_name }} - FastAPI Service
Generated by Governor.py template system
"""

from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel
{% if enable_auth %}
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
{% endif %}

app = FastAPI(title="{{ service_name }}", version="1.0.0")

{% if enable_auth %}
security = HTTPBearer()
{% endif %}


class HealthResponse(BaseModel):
    status: str
    service: str


@app.get("/health", response_model=HealthResponse)
async def health_check():
    """Health check endpoint"""
    return HealthResponse(status="healthy", service="{{ service_name }}")


@app.get("/")
async def root():
    """Root endpoint"""
    return {"message": "{{ service_name }} is running", "docs": "/docs"}


{% if enable_auth %}
@app.get("/protected")
async def protected_endpoint(credentials: HTTPAuthorizationCredentials = Depends(security)):
    """Protected endpoint requiring authentication"""
    token = credentials.credentials
    # Add your authentication logic here
    return {"message": "Access granted", "token": token}
{% endif %}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port={{ service_port }})
